version: "3"

services:
    db:
        image: mysql:8.0.33
        container_name: symfony_db
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local
    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: symfony_phpmyadmin
       ports:
           - "8081:80"
       volumes:
           - "./docker/php/phpmyadmin.ini:/usr/local/etc/php/php.ini"
       environment:
           PMA_ARBRITARY: 1
           PMA_HOST: db
       networks:
           - symfony_app

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:
    mongodb-data: {}
networks:
    symfony_app:
